model_cell_type_signatures:
  epochs: 1
  num_samples: 1000
  batch_size: 2500
  batch_key: 'batch'
  labels_key: 'author_cell_type'
  categorical_covariate_keys: 'assay'

adata_ref_filter:
  cell_count_cutoff: 5
  cell_percentage_cutoff2: 0.3
  nonz_mean_cutoff: 1.12
  n_samples_subset: 1000